<?php

$listeDesActions = array(
    "mentionslegales" => "vues/mentions_legales.php",
    "signalements" => "vues/Signalement/Signalements_List.php",
    "son" => "vues/sound/Sound_Page.php",
    "like" => "vues/likes.php",
    "profil" => "vues/user/profil.php",
    "uploadSound" => "vues/sound/upload_sound.php",
    "soundUpload" => "traitements/sound/upload_sound.php",
    "uploadTutoriel" => "vues/tuto/upload_tutoriel.php",
    "tutorielUpload" => "traitements/tuto/upload_tutoriel.php",
    "profilConfiguration" => "vues/user/profil_conf.php",
    "downloadData" => "traitements/user/download_data.php",
    "reportSound" => "traitements/sound/report_sound.php",
    "soundReport" => "traitements/sound/sound_report.php",
    "downloadSound" => "traitements/sound/download_sound.php",
    "menuAdmin" => "vues/admin/admin_menu.php",
    "register" => "traitements/register.php",
    "setAvatar" => "traitements/user/setAvatar.php",
    "connexion" => "traitements/connexion.php",
    "deconnexion" => "traitements/deconnexion.php",
    "soundFilter" => "traitements/sound/filter.php",
    "soundFilterSearch" => "traitements/sound/filter_search.php",
    "tutoriels" => "vues/tuto/TutoPage.php",
    "cgu" => "vues/user/cgu.php",
    "statistiques" => "vues/admin/stats_générales.php",
    "singleTuto" => "vues/tuto/single_tuto.php",
    "login" => "vues/login.php"
);